# Generated by Django 4.1.3 on 2022-11-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DDOB',
            new_name='DOB',
        ),
    ]
