# Generated by Django 4.1.3 on 2022-11-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_ddob_student_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeday',
            options={'ordering': ['theClass', 'date']},
        ),
        migrations.AlterUniqueTogether(
            name='collegeday',
            unique_together={('date', 'student', 'theClass')},
        ),
    ]
